/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ListOfStatements;
import io.swagger.model.PostStatementDetails;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-11-20T18:24:21.559Z[GMT]")

@Api(value = "statements", description = "the statements API")
public interface StatementsApi {

    @ApiOperation(value = "", nickname = "statementsGet", notes = "Read statements", response = ListOfStatements.class, tags={ "Statements", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Good statements read", response = ListOfStatements.class),
        @ApiResponse(code = 500, message = "Bad statements read") })
    @RequestMapping(value = "/statements",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ListOfStatements> statementsGet();


    @ApiOperation(value = "", nickname = "statementsPost", notes = "Add statement", tags={ "Statements", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Good add statement"),
        @ApiResponse(code = 500, message = "Bad add statement") })
    @RequestMapping(value = "/statements",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> statementsPost(@ApiParam(value = ""  )  @Valid @RequestBody PostStatementDetails body);

}
